baseURL = 'https://info.xbetaa.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'paper'


[params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = true
    repo = "orxbot/info"    # The repo to store comments
    issueTerm = "pathname"

  # giscus
[params.giscus]
  repo = 'orxbot/info'                 # see https://giscus.app for more details
  repoId = 'R_kgDOOShVSQ'
  category = 'General'
  categoryId = 'DIC_kwDOOShVSc4Cos4E'
  mapping = 'pathname'
  theme = 'light'
  lang = 'zh-CN'